### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by coolaj86** [coolaj86/wip-ajscript-cli#1]
- [x] "Hello World"-style vim-ale Fixer
- [x] "Hello World"-style vim-ale Linter w/ LSP over socket
- [ ] integrate prototype parser + fixer https://github.com/GPTScript/AiScript

See also: 
- https://github.com/GPTScript/AiScript/issues/48
- https://github.com/BeyondCodeBootcamp/vim-ale-hello-world
- https://github.com/coolaj86/wip-ajscript-cli
